//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSW.StarCitizen.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSW.StarCitizen.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Citizen : Utils.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run minimized.
        /// </summary>
        internal static string AppOptions_RunMinimized {
            get {
                return ResourceManager.GetString("AppOptions_RunMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on Windows startup.
        /// </summary>
        internal static string AppOptions_RunOnWindowsStartup {
            get {
                return ResourceManager.GetString("AppOptions_RunOnWindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode.
        /// </summary>
        internal static string Game_Mode {
            get {
                return ResourceManager.GetString("Game_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game version.
        /// </summary>
        internal static string Game_Version {
            get {
                return ResourceManager.GetString("Game_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Universe.
        /// </summary>
        internal static string GameMode_LIVE {
            get {
                return ResourceManager.GetString("GameMode_LIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Test Universe.
        /// </summary>
        internal static string GameMode_PTU {
            get {
                return ResourceManager.GetString("GameMode_PTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Star Citizen root folder..
        /// </summary>
        internal static string GamePath_Description {
            get {
                return ResourceManager.GetString("GamePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you select the same Star Citizen folder as when installing the game..
        /// </summary>
        internal static string GamePath_Error_Text {
            get {
                return ResourceManager.GetString("GamePath_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong path to Star Citizen folder.
        /// </summary>
        internal static string GamePath_Error_Title {
            get {
                return ResourceManager.GetString("GamePath_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press here to select Star Citizen root folder.
        /// </summary>
        internal static string GamePath_Hint {
            get {
                return ResourceManager.GetString("GamePath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization {0}.
        /// </summary>
        internal static string Localization_Text {
            get {
                return ResourceManager.GetString("Localization_Text", resourceCulture);
            }
        }
    }
}
