//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSW.StarCitizen.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSW.StarCitizen.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for application update.
        /// </summary>
        internal static string Application_CheckForUpdate_Title {
            get {
                return ResourceManager.GetString("Application_CheckForUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for application updates....
        /// </summary>
        internal static string Application_CheckForUpdates_Text {
            get {
                return ResourceManager.GetString("Application_CheckForUpdates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed install application update.
        /// </summary>
        internal static string Application_FailedInstallUpdate_Text {
            get {
                return ResourceManager.GetString("Application_FailedInstallUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application updates were found.
        /// </summary>
        internal static string Application_NoUpdatesFound_Text {
            get {
                return ResourceManager.GetString("Application_NoUpdatesFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application update.
        /// </summary>
        internal static string Application_Update_Title {
            get {
                return ResourceManager.GetString("Application_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New application version {0} is available.
        ///Do you want download it now?.
        /// </summary>
        internal static string Application_UpdateAvailableDownloadAsk_Text {
            get {
                return ResourceManager.GetString("Application_UpdateAvailableDownloadAsk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New application version {0} is available.
        ///Do you want install it now?.
        /// </summary>
        internal static string Application_UpdateAvailableInstallAsk_Text {
            get {
                return ResourceManager.GetString("Application_UpdateAvailableInstallAsk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Citizen : Utils - v{0}.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Universe.
        /// </summary>
        internal static string GameMode_LIVE {
            get {
                return ResourceManager.GetString("GameMode_LIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Test Universe.
        /// </summary>
        internal static string GameMode_PTU {
            get {
                return ResourceManager.GetString("GameMode_PTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Star Citizen root folder..
        /// </summary>
        internal static string GamePath_Description {
            get {
                return ResourceManager.GetString("GamePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you select the same Star Citizen folder as when installing the game..
        /// </summary>
        internal static string GamePath_Error_Text {
            get {
                return ResourceManager.GetString("GamePath_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong path to Star Citizen folder.
        /// </summary>
        internal static string GamePath_Error_Title {
            get {
                return ResourceManager.GetString("GamePath_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press here to select Star Citizen root folder.
        /// </summary>
        internal static string GamePath_Hint {
            get {
                return ResourceManager.GetString("GamePath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Localization_Add_Text {
            get {
                return ResourceManager.GetString("Localization_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        internal static string Localization_AlwaysOnTop_Text {
            get {
                return ResourceManager.GetString("Localization_AlwaysOnTop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Localization_AutomaticCheck_Measure {
            get {
                return ResourceManager.GetString("Localization_AutomaticCheck_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available versions:.
        /// </summary>
        internal static string Localization_AvailableVersions_Text {
            get {
                return ResourceManager.GetString("Localization_AvailableVersions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable localization.
        /// </summary>
        internal static string Localization_Button_Disable_localization {
            get {
                return ResourceManager.GetString("Localization_Button_Disable_localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable localization.
        /// </summary>
        internal static string Localization_Button_Enable_localization {
            get {
                return ResourceManager.GetString("Localization_Button_Enable_localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Localization_Cancel_Text {
            get {
                return ResourceManager.GetString("Localization_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for localization update.
        /// </summary>
        internal static string Localization_CheckForUpdate_Title {
            get {
                return ResourceManager.GetString("Localization_CheckForUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        internal static string Localization_CheckForUpdates_Text {
            get {
                return ResourceManager.GetString("Localization_CheckForUpdates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new version every.
        /// </summary>
        internal static string Localization_CheckForVersionEvery_Text {
            get {
                return ResourceManager.GetString("Localization_CheckForVersionEvery_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language:.
        /// </summary>
        internal static string Localization_CurrentLanguage {
            get {
                return ResourceManager.GetString("Localization_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display alpha versions.
        /// </summary>
        internal static string Localization_DisplayPreReleases_Text {
            get {
                return ResourceManager.GetString("Localization_DisplayPreReleases_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, it was an error during download. Please try again..
        /// </summary>
        internal static string Localization_Download_ErrorText {
            get {
                return ResourceManager.GetString("Localization_Download_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Error.
        /// </summary>
        internal static string Localization_Download_ErrorTitle {
            get {
                return ResourceManager.GetString("Localization_Download_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Localization_Downloading_Text {
            get {
                return ResourceManager.GetString("Localization_Downloading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository name &apos;{0}&apos; is already exist..
        /// </summary>
        internal static string Localization_DuplicateRepoName_Text {
            get {
                return ResourceManager.GetString("Localization_DuplicateRepoName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository url &apos;{0}&apos; is already exist..
        /// </summary>
        internal static string Localization_DuplicateRepoUrl_Text {
            get {
                return ResourceManager.GetString("Localization_DuplicateRepoUrl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Localization_Error_Title {
            get {
                return ResourceManager.GetString("Localization_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, it was an file error during install. Please ensure install folder and files is not open in other applicaitions..
        /// </summary>
        internal static string Localization_File_ErrorText {
            get {
                return ResourceManager.GetString("Localization_File_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error.
        /// </summary>
        internal static string Localization_File_ErrorTitle {
            get {
                return ResourceManager.GetString("Localization_File_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found new version {0}..
        /// </summary>
        internal static string Localization_Found_New_Version {
            get {
                return ResourceManager.GetString("Localization_Found_New_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode.
        /// </summary>
        internal static string Localization_Game_Mode {
            get {
                return ResourceManager.GetString("Localization_Game_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game version.
        /// </summary>
        internal static string Localization_Game_Version {
            get {
                return ResourceManager.GetString("Localization_Game_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub URL.
        /// </summary>
        internal static string Localization_GitHubURL_Text {
            get {
                return ResourceManager.GetString("Localization_GitHubURL_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, it was an error during installation. Please try again..
        /// </summary>
        internal static string Localization_Install_ErrorText {
            get {
                return ResourceManager.GetString("Localization_Install_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Error.
        /// </summary>
        internal static string Localization_Install_ErrorTitle {
            get {
                return ResourceManager.GetString("Localization_Install_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version:.
        /// </summary>
        internal static string Localization_Installed_Version {
            get {
                return ResourceManager.GetString("Localization_Installed_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string Localization_Installing_Text {
            get {
                return ResourceManager.GetString("Localization_Installing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install update: {0}.
        /// </summary>
        internal static string Localization_InstallUpdateVer_Text {
            get {
                return ResourceManager.GetString("Localization_InstallUpdateVer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install selected version.
        /// </summary>
        internal static string Localization_InstallVersion_Text {
            get {
                return ResourceManager.GetString("Localization_InstallVersion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install version:  {0}.
        /// </summary>
        internal static string Localization_InstallVersion_Title {
            get {
                return ResourceManager.GetString("Localization_InstallVersion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear friend,
        ///We are happy to see the interest to our project.
        ///
        ///But before installation we want to be sure you will read following reminder:
        ///1. Any modification of the game which may give or give any technical advantage over other players or methods provided by developers violate EULA and will be punished with full strength.
        ///2. Changes provided by this modification won&apos;t give you advantage over other players or advantages in methods provided by developers in game or any other kind of advantage. Therefor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Localization_InstallWarning_Text {
            get {
                return ResourceManager.GetString("Localization_InstallWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Localization_InstallWarning_Title {
            get {
                return ResourceManager.GetString("Localization_InstallWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository name is empty..
        /// </summary>
        internal static string Localization_InvalidRepoName_Text {
            get {
                return ResourceManager.GetString("Localization_InvalidRepoName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository url is empty..
        /// </summary>
        internal static string Localization_InvalidRepoUrl_Text {
            get {
                return ResourceManager.GetString("Localization_InvalidRepoUrl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Localization_Language_Text {
            get {
                return ResourceManager.GetString("Localization_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version:.
        /// </summary>
        internal static string Localization_Latest_Version {
            get {
                return ResourceManager.GetString("Localization_Latest_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Localization_Manage_Text {
            get {
                return ResourceManager.GetString("Localization_Manage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Localization_Name_Text {
            get {
                return ResourceManager.GetString("Localization_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access to repository &apos;{0}&apos;.
        /// </summary>
        internal static string Localization_NoRepoAccess_Text {
            get {
                return ResourceManager.GetString("Localization_NoRepoAccess_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No localization updates were found.
        /// </summary>
        internal static string Localization_NoUpdatesFound_Text {
            get {
                return ResourceManager.GetString("Localization_NoUpdatesFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package is corrupted or not valid. Please try another or contact with package owner..
        /// </summary>
        internal static string Localization_Package_ErrorText {
            get {
                return ResourceManager.GetString("Localization_Package_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Error.
        /// </summary>
        internal static string Localization_Package_ErrorTitle {
            get {
                return ResourceManager.GetString("Localization_Package_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Localization_Path_Text {
            get {
                return ResourceManager.GetString("Localization_Path_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press Refresh button.
        /// </summary>
        internal static string Localization_Press_Refresh_Button {
            get {
                return ResourceManager.GetString("Localization_Press_Refresh_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Localization_QuitApp_Text {
            get {
                return ResourceManager.GetString("Localization_QuitApp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Localization_Refresh_Text {
            get {
                return ResourceManager.GetString("Localization_Refresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh available versions.
        /// </summary>
        internal static string Localization_RefreshAvailableVersion_Title {
            get {
                return ResourceManager.GetString("Localization_RefreshAvailableVersion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Localization_Remove_Text {
            get {
                return ResourceManager.GetString("Localization_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository &apos;{0}&apos; used by &apos;{1}&apos;. Do you want remove it?.
        /// </summary>
        internal static string Localization_RemoveUsedRepoWarning_Text {
            get {
                return ResourceManager.GetString("Localization_RemoveUsedRepoWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Citizen : Localization repositories.
        /// </summary>
        internal static string Localization_Repositories_Title {
            get {
                return ResourceManager.GetString("Localization_Repositories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run minimized.
        /// </summary>
        internal static string Localization_RunMinimized_Text {
            get {
                return ResourceManager.GetString("Localization_RunMinimized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run On Windows startup.
        /// </summary>
        internal static string Localization_RunOnStartup_Text {
            get {
                return ResourceManager.GetString("Localization_RunOnStartup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Localization_Settings_Text {
            get {
                return ResourceManager.GetString("Localization_Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source repository:.
        /// </summary>
        internal static string Localization_SourceRepository_Text {
            get {
                return ResourceManager.GetString("Localization_SourceRepository_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start monitoring..
        /// </summary>
        internal static string Localization_Start_Monitoring {
            get {
                return ResourceManager.GetString("Localization_Start_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Localization_StdRepos_Title {
            get {
                return ResourceManager.GetString("Localization_StdRepos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop monitoring..
        /// </summary>
        internal static string Localization_Stop_Monitoring {
            get {
                return ResourceManager.GetString("Localization_Stop_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Localization_Stop_Text {
            get {
                return ResourceManager.GetString("Localization_Stop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Citizen : Localization.
        /// </summary>
        internal static string Localization_Title {
            get {
                return ResourceManager.GetString("Localization_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to uninstall localization. Please ensure install folder and files is not open in other applicaitions..
        /// </summary>
        internal static string Localization_Uninstall_ErrorText {
            get {
                return ResourceManager.GetString("Localization_Uninstall_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall error.
        /// </summary>
        internal static string Localization_Uninstall_ErrorTitle {
            get {
                return ResourceManager.GetString("Localization_Uninstall_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure your are want uninstall localization and remove all files?.
        /// </summary>
        internal static string Localization_Uninstall_QuestionText {
            get {
                return ResourceManager.GetString("Localization_Uninstall_QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall confirmation.
        /// </summary>
        internal static string Localization_Uninstall_QuestionTitle {
            get {
                return ResourceManager.GetString("Localization_Uninstall_QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization removed not fully. Some files can&apos;t be removed..
        /// </summary>
        internal static string Localization_Uninstall_WarningText {
            get {
                return ResourceManager.GetString("Localization_Uninstall_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall warning.
        /// </summary>
        internal static string Localization_Uninstall_WarningTitle {
            get {
                return ResourceManager.GetString("Localization_Uninstall_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string Localization_Uninstalling_Text {
            get {
                return ResourceManager.GetString("Localization_Uninstalling_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall localization.
        /// </summary>
        internal static string Localization_UninstallLocalization_Text {
            get {
                return ResourceManager.GetString("Localization_UninstallLocalization_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New localization version {0} is available.
        ///Do you want download and install it now?.
        /// </summary>
        internal static string Localization_UpdateAvailableInstallAsk_Text {
            get {
                return ResourceManager.GetString("Localization_UpdateAvailableInstallAsk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Http Proxy.
        /// </summary>
        internal static string Localization_UseHttpProxy_Text {
            get {
                return ResourceManager.GetString("Localization_UseHttpProxy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Localization_UserRepos_Title {
            get {
                return ResourceManager.GetString("Localization_UserRepos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package security verification is not passed. Please try another or contact with package owner..
        /// </summary>
        internal static string Localization_Verify_ErrorText {
            get {
                return ResourceManager.GetString("Localization_Verify_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Error.
        /// </summary>
        internal static string Localization_Verify_ErrorTitle {
            get {
                return ResourceManager.GetString("Localization_Verify_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Localization_Warning_Title {
            get {
                return ResourceManager.GetString("Localization_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization {0}.
        /// </summary>
        internal static string LocalizationButton_Text {
            get {
                return ResourceManager.GetString("LocalizationButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;nlog xmlns=&quot;http://www.nlog-project.org/schemas/NLog.xsd&quot;
        ///      xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;variable name=&quot;logDirectory&quot; value=&quot;${basedir}/logs&quot;/&gt;
        ///  &lt;targets&gt;
        ///    &lt;target xsi:type=&quot;ColoredConsole&quot;
        ///            name=&quot;console&quot;
        ///            layout=&quot;${longdate}|${level:uppercase=true}|${logger}|${message}|${exception:format=@}&quot; /&gt;
        ///    &lt;target xsi:type=&quot;File&quot;
        ///            name=&quot;file&quot;
        ///            layout=&quot;${longdate}|${level:uppercase=tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoggingConfig {
            get {
                return ResourceManager.GetString("LoggingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move LIVE to PTU.
        /// </summary>
        internal static string Tools_Move_LIVE_PTU {
            get {
                return ResourceManager.GetString("Tools_Move_LIVE_PTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move PTU to LIVE.
        /// </summary>
        internal static string Tools_Move_PTU_LIVE {
            get {
                return ResourceManager.GetString("Tools_Move_PTU_LIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools_Title {
            get {
                return ResourceManager.GetString("Tools_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///set workpath=%~dp0
        ///set updatepath=%workpath%updates\
        ///set latestpath=%updatepath%latest\
        ///
        ///timeout 1
        ///xcopy &quot;%latestpath%*.*&quot; &quot;%workpath%&quot; /s /k /h /y
        ///if not errorlevel 0 goto update_error
        ///
        ///del &quot;%updatepath%latest.json&quot;
        ///del &quot;%updatepath%latest.zip&quot;
        ///del /q &quot;%latestpath%*&quot;
        ///for /d %%p in (&quot;%latestpath%*.*&quot;) do rmdir /s /q &quot;%%p&quot;
        ///rmdir /s /q &quot;%latestpath%&quot;
        ///
        ///start &quot;&quot; &quot;%workpath%SCTools.exe&quot; update_status 0
        ///exit
        ///
        ///:update_error
        ///
        ///start &quot;&quot; &quot;%workpath%SCTools.exe&quot; update_status 1&quot;
        ///exit.
        /// </summary>
        internal static string UpdateScript {
            get {
                return ResourceManager.GetString("UpdateScript", resourceCulture);
            }
        }
    }
}
